- name: update apt cache
  apt:
    update_cache: yes

- name: ensure basic apps present
  apt:
    name: 
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - virtualenv
      - nginx
      - git
    state: present

- name: ensure nginx started
  systemd:
    name: nginx
    state: started

- name: deploy all apps
  include_tasks: deploy_app_tasks.yml
  loop: "{{ flask_apps }}"
  loop_control:
    loop_var: app