- hosts: appserver
  become: yes
  serial: 1 # all hosts in groups will be handled one by one
  vars:
    flask_upgrade_apps: yes
    
  pre_tasks:
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: balancer
      # loop: "{{ groups.balancers }}"

  roles:
    - flaskapp

  post_tasks:
    - name: Wait for backend to come back up.
      wait_for:
        host: '{{ inventory_hostname }}'
        port: 80
        state: started
        timeout: 60

    - name: Enable the backend server in HAProxy.
      haproxy:
        state: enabled
        host: '{{ inventory_hostname }}'
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: balancer
      loop: "{{ groups.balancers }}"


